In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(23,56, (4,5))

In [3]:
arr1

array([[49, 55, 43, 41, 24],
       [39, 34, 53, 29, 29],
       [31, 44, 37, 48, 39],
       [46, 44, 45, 27, 27]])

In [4]:
arr2 = np.random.randint(34,67, (4,5))

In [5]:
arr1

array([[49, 55, 43, 41, 24],
       [39, 34, 53, 29, 29],
       [31, 44, 37, 48, 39],
       [46, 44, 45, 27, 27]])

In [6]:
arr2

array([[53, 48, 52, 35, 57],
       [43, 56, 63, 35, 52],
       [37, 52, 35, 63, 66],
       [58, 56, 50, 49, 47]])

In [7]:
np.concatenate((arr1,arr2))

array([[49, 55, 43, 41, 24],
       [39, 34, 53, 29, 29],
       [31, 44, 37, 48, 39],
       [46, 44, 45, 27, 27],
       [53, 48, 52, 35, 57],
       [43, 56, 63, 35, 52],
       [37, 52, 35, 63, 66],
       [58, 56, 50, 49, 47]])

In [8]:
np.concatenate((arr1,arr2), axis=1)


array([[49, 55, 43, 41, 24, 53, 48, 52, 35, 57],
       [39, 34, 53, 29, 29, 43, 56, 63, 35, 52],
       [31, 44, 37, 48, 39, 37, 52, 35, 63, 66],
       [46, 44, 45, 27, 27, 58, 56, 50, 49, 47]])

In [9]:
np.hstack((arr1,arr2))

array([[49, 55, 43, 41, 24, 53, 48, 52, 35, 57],
       [39, 34, 53, 29, 29, 43, 56, 63, 35, 52],
       [31, 44, 37, 48, 39, 37, 52, 35, 63, 66],
       [46, 44, 45, 27, 27, 58, 56, 50, 49, 47]])

In [10]:
np.vstack((arr1, arr2))

array([[49, 55, 43, 41, 24],
       [39, 34, 53, 29, 29],
       [31, 44, 37, 48, 39],
       [46, 44, 45, 27, 27],
       [53, 48, 52, 35, 57],
       [43, 56, 63, 35, 52],
       [37, 52, 35, 63, 66],
       [58, 56, 50, 49, 47]])

In [11]:
arr1

array([[49, 55, 43, 41, 24],
       [39, 34, 53, 29, 29],
       [31, 44, 37, 48, 39],
       [46, 44, 45, 27, 27]])

In [12]:
np.split(arr1, [2,4])

[array([[49, 55, 43, 41, 24],
        [39, 34, 53, 29, 29]]),
 array([[31, 44, 37, 48, 39],
        [46, 44, 45, 27, 27]]),
 array([], shape=(0, 5), dtype=int32)]

In [13]:
np.split(arr1, [0,2,6])


[array([], shape=(0, 5), dtype=int32),
 array([[49, 55, 43, 41, 24],
        [39, 34, 53, 29, 29]]),
 array([[31, 44, 37, 48, 39],
        [46, 44, 45, 27, 27]]),
 array([], shape=(0, 5), dtype=int32)]

In [14]:
arr1

array([[49, 55, 43, 41, 24],
       [39, 34, 53, 29, 29],
       [31, 44, 37, 48, 39],
       [46, 44, 45, 27, 27]])

In [15]:
np.split(arr1, 2)

[array([[49, 55, 43, 41, 24],
        [39, 34, 53, 29, 29]]),
 array([[31, 44, 37, 48, 39],
        [46, 44, 45, 27, 27]])]

In [16]:
np.split(arr1, 3)


ValueError: array split does not result in an equal division

In [ ]:
arr1

In [ ]:
np.split(arr1, [2,4], axis=1)

In [ ]:
np.split(arr1, 3, axis=1)

In [ ]:
np.split(arr1, 5, axis=1)


In [ ]:
arr1

In [ ]:
np.split(arr1, [2,5,7], axis=1)

In [ ]:
np.split(arr1, [0,2,5,7], axis=1)


In [ ]:
np.split(arr1, [0,2], axis=1)


In [ ]:
print(dir(np))

In [ ]:
arr1

In [ ]:
arr1.ravel()

In [ ]:
arr1.flatten()

In [17]:
arr = np.array([4,3,5,7,8])
arr

array([4, 3, 5, 7, 8])

In [18]:
arr.cumsum()

array([ 4,  7, 12, 19, 27])

In [19]:
arr

array([4, 3, 5, 7, 8])

In [20]:
np.argmin(arr)

1

In [21]:
np.argmax(arr)

4

In [22]:
arr

array([4, 3, 5, 7, 8])

In [23]:
np.argsort(arr)

array([1, 0, 2, 3, 4], dtype=int64)

In [24]:
arr1

array([[49, 55, 43, 41, 24],
       [39, 34, 53, 29, 29],
       [31, 44, 37, 48, 39],
       [46, 44, 45, 27, 27]])

In [25]:
np.argmin(arr1)

4

In [26]:
np.argmin(arr1, axis=0)


array([2, 1, 2, 3, 0], dtype=int64)

In [27]:
arr1

array([[49, 55, 43, 41, 24],
       [39, 34, 53, 29, 29],
       [31, 44, 37, 48, 39],
       [46, 44, 45, 27, 27]])

In [28]:
np.nan

nan

In [29]:
np.full((3,4), fill_value=np.nan)

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [30]:
arr1

array([[49, 55, 43, 41, 24],
       [39, 34, 53, 29, 29],
       [31, 44, 37, 48, 39],
       [46, 44, 45, 27, 27]])

In [34]:
arr1.T

array([[49, 39, 31, 46],
       [55, 34, 44, 44],
       [43, 53, 37, 45],
       [41, 29, 48, 27],
       [24, 29, 39, 27]])

In [35]:
arr1.transpose()

array([[49, 39, 31, 46],
       [55, 34, 44, 44],
       [43, 53, 37, 45],
       [41, 29, 48, 27],
       [24, 29, 39, 27]])

In [36]:
np.transpose(arr1)

array([[49, 39, 31, 46],
       [55, 34, 44, 44],
       [43, 53, 37, 45],
       [41, 29, 48, 27],
       [24, 29, 39, 27]])

## Image manipulation