In [1]:
import numpy as np

In [2]:
np.array([10,20,30,40,50])

array([10, 20, 30, 40, 50])

In [3]:
ls = [[10,20,30],[40,50,60],[70,80,90]]

In [4]:
arr_2d = np.array(ls)
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [5]:
arr_2d.ndim

2

In [6]:
arr_2d.size

9

In [7]:
arr_2d.dtype

dtype('int32')

In [8]:
arr_2d.shape

(3, 3)

### indexing & Slicing 


                syntax:
                        indexing:
                                    arr[row_index, col_index]
                        slicing:
                                    arr[row_sclicing, col_slicing]

In [9]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr_2d[1]

array([40, 50, 60])

In [11]:
arr_2d[-1]

array([70, 80, 90])

In [12]:
arr_2d[1][-1]

60

In [13]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
arr_2d[0:2, 1:3]

array([[20, 30],
       [50, 60]])

In [15]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
arr_2d[::2,:]


array([[10, 20, 30],
       [70, 80, 90]])

In [17]:
arr_2d[::2,::-1]

array([[30, 20, 10],
       [90, 80, 70]])

In [18]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [19]:
arr_2d[:, 1]

array([20, 50, 80])

In [20]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
arr_2d > 50

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [22]:
arr_2d[arr_2d > 50]


array([60, 70, 80, 90])

In [23]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,4,6,8,10,12])

In [24]:
arr1

array([10, 20, 30, 40, 50, 60])

In [25]:
arr1 > 10

array([False,  True,  True,  True,  True,  True])

In [26]:
arr1 + 10

array([20, 30, 40, 50, 60, 70])

In [27]:
arr1 / 10

array([1., 2., 3., 4., 5., 6.])

In [28]:
arr1

array([10, 20, 30, 40, 50, 60])

In [29]:
arr1 * 20

array([ 200,  400,  600,  800, 1000, 1200])

In [30]:
arr1

array([10, 20, 30, 40, 50, 60])

In [31]:
arr2

array([ 2,  4,  6,  8, 10, 12])

In [32]:
arr1 + arr2

array([12, 24, 36, 48, 60, 72])

In [33]:
arr1 - arr2

array([ 8, 16, 24, 32, 40, 48])

In [34]:
arr1 / arr2

array([5., 5., 5., 5., 5., 5.])

    quan   price    sell price
     5      400       500

In [35]:
%%writefile data.csv
quan,price,sell_price
5,400,600
10,500,800
3,400,500
8,200,500

Overwriting data.csv


In [36]:
data = np.genfromtxt('data.csv', dtype=np.int16, delimiter=',', skip_header=1)
data

array([[  5, 400, 600],
       [ 10, 500, 800],
       [  3, 400, 500],
       [  8, 200, 500]], dtype=int16)

In [37]:
data

array([[  5, 400, 600],
       [ 10, 500, 800],
       [  3, 400, 500],
       [  8, 200, 500]], dtype=int16)

In [38]:
sell_price = data[:, 2]
sell_price

array([600, 800, 500, 500], dtype=int16)

In [39]:
actual_price = data[:, 1]
actual_price

array([400, 500, 400, 200], dtype=int16)

In [40]:
quan = data[:,0]
quan

array([ 5, 10,  3,  8], dtype=int16)

In [41]:
(sell_price - actual_price) * quan

array([1000, 3000,  300, 2400], dtype=int16)

In [42]:
((sell_price - actual_price) * quan).sum()


6700

In [44]:
arr = np.random.randint(30, 50, 16)
arr

array([45, 48, 44, 37, 38, 39, 48, 40, 48, 46, 34, 35, 32, 31, 46, 42])

In [46]:
arr_2d = arr.reshape((4,4))
arr_2d

array([[45, 48, 44, 37],
       [38, 39, 48, 40],
       [48, 46, 34, 35],
       [32, 31, 46, 42]])

In [49]:
print(dir(arr_2d))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [50]:
arr_2d

array([[45, 48, 44, 37],
       [38, 39, 48, 40],
       [48, 46, 34, 35],
       [32, 31, 46, 42]])

In [47]:
arr_2d.mean()

40.8125

In [48]:
arr_2d.sum()

653

In [51]:
arr_2d.sum(axis=1)

array([174, 165, 163, 151])

In [52]:
45+48+44+37

174

In [53]:
arr_2d

array([[45, 48, 44, 37],
       [38, 39, 48, 40],
       [48, 46, 34, 35],
       [32, 31, 46, 42]])

In [54]:
arr_2d.mean(axis=1)

array([43.5 , 41.25, 40.75, 37.75])

In [55]:
arr_2d

array([[45, 48, 44, 37],
       [38, 39, 48, 40],
       [48, 46, 34, 35],
       [32, 31, 46, 42]])

In [57]:
(arr_2d.sum(axis=1)  / 400) * 100

array([43.5 , 41.25, 40.75, 37.75])

In [58]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

    np.arange()
    np.random.randint()
    np.linspace()
    np.eye()
    np.empty()
    np.null()
    np.ones()
    np.zeros()
    

In [59]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [61]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [62]:
np.arange(0, 1.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [63]:
np.arange(1, 11, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [64]:
arr = np.arange(15, 31)
arr

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
arr.size

16

In [66]:
arr.reshape((4,4))

array([[15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [67]:
arr.reshape((2,8))


array([[15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30]])

In [68]:
arr.reshape((8,2))


array([[15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30]])